### PR TITLE
Check if ref name is a jinja var before add to models

### PR DESCRIPTION
**Pull request by Hosuke**
Demo trace:
when ref name is a JINJA var (like dex_trades)
image
when ref name is not a JINJA var (not in {% block %} in the file)
image

### CODE REVIEW

**Comment by augustog** [comment]
@Hosuke thanks so much for this contribution!

The review from Meghan may take a bit longer as she's off for a few days this week. One of the points she brought up is that we should ideally write unit tests for these, as it's otherwise very hard to test them out.

I'd especially be on the lookout for cases of false positives. Can you think of any cases where the regex may match sth that is _not_ a jinja var?

Do you think it's something we could try out with this PR?

**Comment by Hosuke** [comment]
> @Hosuke thanks so much for this contribution!
> 
> The review from Meghan may take a bit longer as she's off for a few days this week. One of the points she brought up is that we should ideally write unit tests for these, as it's otherwise very hard to test them out.
> 
> I'd especially be on the lookout for cases of false positives. Can you think of any cases where the regex may match sth that is _not_ a jinja var?

That's a good question, the more robust approach would be actually run the JINJA compilation before the pre-hook.
I use `{%block_content%}` to determine the jinja var, and `{%block_content%}` must be in one line.
A strengthen match I can come out so far would be, make sure `src_value_ref` not being wrapped by `'` or `"` in the block_content.

**Comment by dot2dotseurat** [comment]
hi @Hosuke, sorry this took me so long to review. I'm recovering from the flu.

I've added a commit, feel free to delete it, to illustrate where we should be extending the unit test. 

I'm not entirely sure what your addition to the hook does yet. Can you write an extension to this unit test to show what false positive or false negative your change protects against? 

That should include a short SQL statement and the expected results. I added to test_check_script_ref_and_source_integration by appending a new example to TESTS_INTEGRATION which includes a SQL statement, expected results code, and whether the test had a "valid manifest". Feel free to add to test_check_script_ref_and_source instead. 

Then I used pytest locally to run the test and confirm the results. Ideally, we'll integrate pytest to run in the pull request but we haven't done it yet.  (We should be able to use tox for this but looked briefly and didn't get it working).

Can you write a new test (maybe off main without your changes) for a false positive or negative and confirm the test fails and then run it against your changes to confirm the test passes? Maybe add a short comment describing the problem you're fixing? 


```
/Users/me/.virtualenvs/spellbook-y-Dw_mx-/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py --path /Users/me/src/pre-commit-dbt/tests/unit/test_script_ref_and_source.py
Testing started at 1:03 PM ...
Launching pytest with arguments /Users/me/src/pre-commit-dbt/tests/unit/test_script_ref_and_source.py --no-header --no-summary -q in /Users/me/src/pre-commit-dbt/tests/unit

============================= test session starts ==============================
collecting ... collected 9 items

test_script_ref_and_source.py::test_check_script_ref_and_source[\n    SELECT * FROM {{ ref('ref1') }} bb\n    JOIN {{ source('src', 'src1') }} sr1 ON bb.id = sr1.id\n    JOIN {{ ref('ref2') }} r ON bb.id = r.id\n    JOIN {{ source('src', 'src2') }} sr2 ON bb.id = sr2.id\n    -0-missing_models0-missing_source0] 
test_script_ref_and_source.py::test_check_script_ref_and_source[\n    SELECT * FROM {{ ref("ref1") }} bb\n    JOIN {{ ref("ref2") }} r ON bb.id = r.id\n    JOIN {{ source("src", "src1") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src2") }} sr2 ON bb.id = sr2.id\n    -0-missing_models1-missing_source1] 
test_script_ref_and_source.py::test_check_script_ref_and_source[\n    SELECT * FROM {{ ref("ref1") }} bb\n    JOIN {{ ref("ref3") }} r ON bb.id = r.id\n    JOIN {{ source("src", "src1") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src3") }} sr2 ON bb.id = sr2.id\n    -1-missing_models2-missing_source2] 
test_script_ref_and_source.py::test_check_script_ref_and_source[\n    SELECT * FROM {{ ref("ref1") }} bb\n    JOIN {{ source("src", "src1") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src3") }} sr2 ON bb.id = sr2.id\n    -1-missing_models3-missing_source3] 
test_script_ref_and_source.py::test_check_script_ref_and_source[\n    SELECT * FROM {{ ref("ref4") }} bb\n    JOIN {{ ref("ref3") }} r ON bb.id = r.id\n    JOIN {{ source("src", "src4") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src3") }} sr2 ON bb.id = sr2.id\n    -1-missing_models4-missing_source4] 
test_script_ref_and_source.py::test_check_script_ref_and_source_integration[\n    SELECT * FROM {{ ref("ref1") }} bb\n    JOIN {{ ref("ref2") }} r ON bb.id = r.id\n    JOIN {{ source("src", "src1") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src2") }} sr2 ON bb.id = sr2.id\n    -0-True] 
test_script_ref_and_source.py::test_check_script_ref_and_source_integration[\n    SELECT * FROM aa\n    -0-True] 
test_script_ref_and_source.py::test_check_script_ref_and_source_integration[\n    SELECT * FROM {{ ref("ref1") }} bb\n    JOIN {{ ref("ref3") }} r ON bb.id = r.id\n    JOIN {{ source("src", "src1") }} sr1 ON bb.id = sr1.id\n    JOIN {{ source("src", "src3") }} sr2 ON bb.id = sr2.id\n    -1-False] 
test_script_ref_and_source.py::test_check_script_ref_and_source_integration[\n    WITH aa as\n    (SELECT *\n    FROM  {{ ref("ref1") }} bb)\n    SELECT *\n    from aa\n    -1-True] PASSED [ 11%]PASSED [ 22%]PASSED [ 33%]Missing source `src.src3`
Missing model (ref) ref3
PASSED [ 44%]Missing source `src.src3`
PASSED [ 55%]Missing source `src.src4`
Missing source `src.src3`
Missing model (ref) ref3
Missing model (ref) ref4
PASSED [ 66%]PASSED [ 77%]PASSED [ 88%]Unable to load manifest file ([Errno 2] No such file or directory: 'target/manifest.json')
FAILED [100%]
tests/unit/test_script_ref_and_source.py:131 (test_check_script_ref_and_source_integration[\n    WITH aa as\n    (SELECT *\n    FROM  {{ ref("ref1") }} bb)\n    SELECT *\n    from aa\n    -1-True])
0 != 1

Expected :1
Actual   :0
<Click to see difference>

input_s = '\n    WITH aa as\n    (SELECT *\n    FROM  {{ ref("ref1") }} bb)\n    SELECT *\n    from aa\n    '
expected_status_code = 1, valid_manifest = True
manifest_path_str = '/private/var/folders/nw/xzhc52090l114y_l297x2fr80000gn/T/pytest-of-me/pytest-19/test_check_script_ref_and_sour8/target/manifest.json'
tmpdir = local('/private/var/folders/nw/xzhc52090l114y_l297x2fr80000gn/T/pytest-of-me/pytest-19/test_check_script_ref_and_sour8')

    @pytest.mark.parametrize(
        ("input_s", "expected_status_code", "valid_manifest"), TESTS_INTEGRATION
    )
    def test_check_script_ref_and_source_integration(
        input_s, expected_status_code, valid_manifest, manifest_path_str, tmpdir
    ):
        path = tmpdir.join("file.sql")
        path.write_text(input_s, "utf-8")
        if valid_manifest:
            manifest_args = ["--manifest", manifest_path_str]
        else:
            manifest_args = []
        input_args = [str(path)]
        input_args.extend(manifest_args)
        ret = main(input_args)
    
>       assert ret == expected_status_code
E       assert 0 == 1

test_script_ref_and_source.py:148: AssertionError
```

**Comment by dot2dotseurat** [comment]
I'm reminded now after looking at @soispoke 's DAO [PR](https://github.com/duneanalytics/spellbook/pull/1940#discussion_r1025801488). This change is supposed to fix the issue where variables we loop through like in dao.proposals aren't recognized as models? Is that correct? 

I replaced my mock test with the sql statement from Thomas's spell as the test. 

Looks like it passed. Great work.

**Review by dot2dotseurat — APPROVED** [review]

**Comment by jeff-dude** [comment]
> I'm reminded now after looking at @soispoke 's DAO [PR](https://github.com/duneanalytics/spellbook/pull/1940#discussion_r1025801488). This change is supposed to fix the issue where variables we loop through like in dao.proposals aren't recognized as models? Is that correct?
> 
> I replaced my mock test with the sql statement from Thomas's spell as the test.
> 
> Looks like it passed. Great work.

yes, same for dex and other models following pattern. thanks for this both!

**Comment by Hosuke** [comment]
The next step would be change [this line](https://github.com/duneanalytics/spellbook/blob/main/.pre-commit-config.yaml#L4) to point to this repo, and make a release with v1.0.0. The release will enable pre-commit to run locally(as `pre-commit run --hook-stage manual` will fetch from the tag's source).

**Comment by jeff-dude** [comment]
yes, agreed, i have that changed in a local branch right now -- but we can push a specific branch to do just that change to make it happen sooner if we want?
cc @dot2dotseurat what do you think? proceed with fork repo change asap?

**Comment by Hosuke** [comment]
Also, I am thinking that we can keep two versions of `check-script-ref-and-source.py` script. Keep the original one for PRs submitted to merge to dune/spellbook main branch. We may(I am not sure) actually compile the JINJA template before the pre-commit check in the github action/cicd.

**Comment by jeff-dude** [comment]
i think we should be able to monitor the change (once repo is redirected in spellbook) and go from there, it may be that we can just keep this one

**Comment by dot2dotseurat** [comment]
@jeff-dude let's do it Monday morning. Sorry, I missed this until now. I have no reason to think switching will break anything but it's always nicer not to be scrambling on a Friday if something unexpected happens.

**Pull request merged**
